// =====================================================
// WCIF 2026 - 사이트 콘텐츠 데이터 (v2)
// 이 파일은 admin.html 에서 수정할 수 있습니다.
// 직접 수정해도 됩니다 (수정 후 사이트 새로고침).
// =====================================================
window.WCIF_CONTENT = {
  "popups": [
    {
      "id": "hackathon", "enabled": false, "url": "hackathon.html",
      "kor": {
        "label": "Hackathon",
        "title": "해커톤 참가자 모집",
        "lines": [
          "하이프크래프트 · WCIF 문화 해커톤",
          "모집 · 2026.06.16(화) ~ 06.22(월) 17:00",
          "대구·수성구의 유휴 공간을 문화로 되살리는 청년 아이디어 경진대회"
        ],
        "btn": "해커톤 신청 안내 보기",
        "hide": "오늘 하루 보지 않기",
        "close": "닫기"
      },
      "eng": {
        "label": "Hackathon",
        "title": "Hackathon Open Call",
        "lines": [
          "Hypercraft · WCIF Culture Hackathon",
          "Applications · Jun 16 (Tue) – Jun 22 (Mon), 2026, 17:00",
          "An idea competition reviving idle spaces in Daegu & Suseong-gu through culture"
        ],
        "btn": "View Hackathon Details",
        "hide": "Don't show again today",
        "close": "Close"
      }
    },
    {
      "id": "futurestage", "enabled": false, "url": "https://us02web.zoom.us/j/86364526296?pwd=4mgQmaGa2oOTuunPrRBqmyzlLlMrli.1#success",
      "kor": {
        "label": "Future Stage",
        "title": "퓨처 스테이지 안내",
        "lines": [
          "퓨처 스테이지 : 컬쳐&트렌드 인사이트",
          "트렌드세터들의 자유로운 오픈 팟캐스트",
          "2026.07.02(목) · 14:15~17:40 · 수성스퀘어 피오니홀"
        ],
        "btn": "온라인 참여 바로가기",
        "hide": "오늘 하루 보지 않기",
        "close": "닫기"
      },
      "eng": {
        "label": "Future Stage",
        "title": "Future Stage",
        "lines": [
          "Future Stage: Culture & Trend Insight",
          "Free, open podcasts by trendsetters",
          "Jul 2 (Thu) · 14:15~17:40 · Peony Hall, Suseong Square"
        ],
        "btn": "Join Online",
        "hide": "Don't show again today",
        "close": "Close"
      }
    }
  ],
  "registration": {
    "enabled": false,
    "url": "register.html",
    "kor": {
      "label": "2026 세계문화산업포럼",
      "highlight": "[7.2-3 · 호텔수성]",
      "btn": "사전등록 바로가기"
    },
    "eng": {
      "label": "2026 World Cultural Industry Forum",
      "highlight": "[JUL 2-3 · HOTEL SUSUNG]",
      "btn": "Register Now"
    }
  },
  "schedule": [
    {
      "kor": { "tag": "DAY 1 · 7.2(목)", "title": "" },
      "eng": { "tag": "DAY 1 · Jul 2", "title": "" },
      "items": [
        { "sec": true, "kor": { "title": "OPENING" }, "eng": { "title": "OPENING" } },
        { "time": "14:15-14:30", "kor": { "title": "개회사 · 축사", "who": [ { "role": "개회사", "members": ["이장우|세계문화산업포럼 의장"] }, { "role": "축사", "members": ["김승수|국회의원", "김대권|대구광역시 수성구청장", "박창식|한국국제문화교류진흥원 원장(전 제19대 국회의원)"] } ] }, "eng": { "title": "Opening & Congratulatory Remarks", "who": [ { "role": "Opening", "members": ["Lee Jang-woo|Chair, WCIF"] }, { "role": "Congratulatory", "members": ["Kim Seung-su|Member of the National Assembly", "Kim Dae-kwon|Mayor of Suseong-gu", "Park Chang-sik|President, KOFICE (Former Member of the 19th National Assembly)"] } ] } },
        { "sec": true, "kor": { "title": "Track 1 · 문화를 기반으로 한 도시발전 전략" }, "eng": { "title": "Track 1 · Culture-Based Urban Development Strategy" } },
        { "sec": true, "lv": 2, "kor": { "title": "SESSION 1 · 도시 디자인" }, "eng": { "title": "SESSION 1 · Urban Design" } },
        { "time": "14:30-14:45", "kor": { "title": "[기조연설] 아트뮤지엄시티 수성", "who": [ { "role": "발표자", "members": ["존 홍|서울대학교 건축학과 교수"] } ] }, "eng": { "title": "[Keynote] Art Museum City Suseong", "who": [ { "role": "Speaker", "members": ["John Hong|Professor, Seoul National University"] } ] } },
        { "time": "14:45-14:55", "kor": { "title": "[기조발표] 자유로운 건축, 살아있는 도시", "who": [ { "role": "발표자", "members": ["이시가미 준야|준야 이시가미+어소시에이트 대표이사|jp"] } ] }, "eng": { "title": "[Keynote Presentation] Free Architecture, Living City", "who": [ { "role": "Speaker", "members": ["Junya Ishigami|President, junya.ishigami+associates|jp"] } ] } },
        { "time": "14:55-15:05", "kor": { "title": "[기조발표] 도시디자인과 사회적연대: 수성구를 중심으로", "who": [ { "role": "발표자", "members": ["믈라덴 야드리치|야드리치 아르히텍투어 대표 건축가|at"] } ] }, "eng": { "title": "[Keynote Presentation] Urban Design and Social Solidarity: A Focus on Suseong-gu", "who": [ { "role": "Speaker", "members": ["Mladen Jadric|Architect, Jadric Architektur|at"] } ] } },
        { "time": "15:05-15:15", "kor": { "title": "[발제] 공간디자인과 도시발전의 미래", "who": [ { "role": "발표자", "members": ["김영섭|㈜김영섭건축문화건축사사무소 대표 건축사"] } ] }, "eng": { "title": "[Presentation] Spatial Design and the Future of Urban Development", "who": [ { "role": "Speaker", "members": ["Kim Young-sub|Principal Architect"] } ] } },
        { "time": "15:15-15:55", "kor": { "title": "[대담] 도시를 디자인하는 문화의 힘", "who": [ { "role": "모더레이터", "members": ["김영섭|㈜김영섭건축문화건축사사무소 대표 건축사"] }, { "role": "패널", "members": ["김홍근|㈜건축사사무소 ADF건축 대표 건축가", "전인건|간송미술관 관장", "존 홍|서울대학교 건축학과 교수"] } ] }, "eng": { "title": "[Panel] The Power of Culture in Designing Cities", "who": [ { "role": "Moderator", "members": ["Kim Young-sub|Principal Architect"] }, { "role": "Panel", "members": ["Kim Hong-geun|Architect, ADF Architects", "Jun In-kun|Director, Kansong Art Museum", "John Hong|Professor, Seoul National University"] } ] } },
        { "sec": true, "lv": 2, "kor": { "title": "SESSION 2 · 도시 브랜딩" }, "eng": { "title": "SESSION 2 · City Branding" } },
        { "time": "15:55-16:10", "kor": { "title": "[기조연설] 문화기반의 도시 브랜딩", "who": [ { "role": "발표자", "members": ["류재현|2026 세계문화유산축전 가야고분군 총감독"] } ] }, "eng": { "title": "[Keynote] Culture-Based City Branding", "who": [ { "role": "Speaker", "members": ["Ryu Jae-hyun|Artistic Director, 2026 WHF Gaya Tumuli"] } ] } },
        { "time": "16:10-17:00", "kor": { "title": "[대담] K-로컬 브랜딩의 글로벌 성공 전략", "who": [ { "role": "모더레이터", "members": ["서병기|대중문화평론가"] }, { "role": "패널", "members": ["류재현|2026 세계문화유산축전 가야고분군 총감독", "노희영|히노컨설팅펌 대표이사", "유정수|글로우서울 대표이사"] } ] }, "eng": { "title": "[Panel] Global Success Strategies for K-Local Branding", "who": [ { "role": "Moderator", "members": ["Suh Byung-ki|Pop Culture Critic"] }, { "role": "Panel", "members": ["Ryu Jae-hyun|Artistic Director, 2026 WHF Gaya Tumuli", "Noh Hee-young|CEO, Hino Consulting Firm", "Yu Jung-su|CEO, Glow Seoul"] } ] } },
        { "sec": true, "lv": 2, "kor": { "title": "SESSION 3 · 도시 콘텐츠" }, "eng": { "title": "SESSION 3 · Urban Content" } },
        { "time": "17:00-17:50", "kor": { "title": "[대담] 도시콘텐츠의 새로운 엔진", "who": [ { "role": "모더레이터", "members": ["이정우|㈜써클커넥션 대표이사"] }, { "role": "패널", "members": ["최원석|프로젝트렌트 대표이사", "백아람|누리하우스 주식회사 대표이사", "홍주석|어반플레이 대표이사"] } ] }, "eng": { "title": "[Panel] New Engines of Urban Content", "who": [ { "role": "Moderator", "members": ["Lee Jung-woo|CEO, Circle Connection, Inc."] }, { "role": "Panel", "members": ["Choi Won-suk|CEO, Project Rent", "Baek A-ram|CEO, Nurihaus", "Hong Joo-suk|CEO, Urbanplay"] } ] } },
        { "sec": true, "kor": { "title": "환영 만찬" }, "eng": { "title": "Welcome Dinner" } },
        { "time": "18:00-20:00", "kor": { "title": "", "who": [ { "role": "축사", "members": ["이인선|국회의원", "강은희|대구시교육청 교육감", "오부치 유코|일본 중의원 의원|jp"] }, { "role": "7th WCIF AWARD", "members": ["이수만|A2O엔터테인먼트 키 프로듀서||수상자"] }, { "role": "DIMF 20주년 기념공연", "members": ["최민철|뮤지컬배우", "리사|뮤지컬배우"] } ] }, "eng": { "title": "", "who": [ { "role": "Congratulatory", "members": ["Lee In-seon|Member of the National Assembly", "Kang Eun-hee|Superintendent, Daegu Metropolitan Office of Education", "Yuko Obuchi|Member of the House of Representatives, Japan|jp"] }, { "role": "7th WCIF AWARD", "members": ["Lee Soo-man|Key Producer, A2O Entertainment||Laureate"] }, { "role": "DIMF 20th Anniv. Performance", "members": ["Choi Min-chul|Musical Actor", "Lisa|Musical Actor"] } ] } }
      ]
    },
    {
      "kor": { "tag": "DAY 2 · 7.3(금)", "title": "" },
      "eng": { "tag": "DAY 2 · Jul 3", "title": "" },
      "items": [
        { "sec": true, "kor": { "title": "OPENING" }, "eng": { "title": "OPENING" } },
        { "time": "09:30-09:40", "kor": { "title": "", "who": [ { "role": "환영사", "members": ["김대권|대구광역시 수성구청장"] } ] }, "eng": { "title": "", "who": [ { "role": "Welcome", "members": ["Kim Dae-kwon|Mayor of Suseong-gu"] } ] } },
        { "time": "09:40-09:55", "kor": { "title": "", "who": [ { "role": "축사", "members": ["주호영|국회의원(전 한일의원연맹 회장)", "오부치 유코|일본 중의원 의원|jp"] } ] }, "eng": { "title": "", "who": [ { "role": "Congratulatory", "members": ["Joo Ho-young|Member of the National Assembly (Former Chairman, Korea-Japan Parliamentarians' Union)", "Yuko Obuchi|Member of the House of Representatives, Japan|jp"] } ] } },
        { "sec": true, "kor": { "title": "MAIN · 한일 협력 특별세미나: 도시 간 협력을 통한 문화관광 활성화" }, "eng": { "title": "MAIN · Korea-Japan Special Seminar: Revitalizing Cultural Tourism" } },
        { "time": "09:55-10:05", "kor": { "title": "[기조연설] 도시발전과 녹색성장", "who": [ { "role": "발표자", "members": ["김상협|글로벌녹색성장기구 사무총장"] } ] }, "eng": { "title": "[Keynote] Urban Development and Green Growth", "who": [ { "role": "Speaker", "members": ["Kim Sang-hyup|Director-General, GGGI"] } ] } },
        { "time": "10:05-10:35", "kor": { "title": "[초청연설] 도시 간 협력을 통한 한국과 일본의 관광 활성화", "who": [ { "role": "발표자", "members": ["호리코시 마사카츠|일본 시부카와시 부시장|jp", "김대권|대구광역시 수성구청장"] } ] }, "eng": { "title": "[Invited Speech] Revitalizing Korea-Japan Tourism Through Cross-City Cooperation", "who": [ { "role": "Speaker", "members": ["Masakatsu Horikoshi|Deputy Mayor, Shibukawa City|jp", "Kim Dae-kwon|Mayor of Suseong-gu"] } ] } },
        { "time": "10:35-11:45", "kor": { "title": "[대담] What's Next?", "who": [ { "role": "모더레이터", "members": ["서민교|대구대학교 명예교수"] }, { "role": "패널", "members": ["호리코시 마사카츠|일본 시부카와시 부시장|jp", "윤민호|일본국제금융정보센터 특임연구위원실장", "엄찬용|트립서포터즈 대표", "김대권|대구광역시 수성구청장"] } ] }, "eng": { "title": "[Panel] What's Next?", "who": [ { "role": "Moderator", "members": ["Suh Min-kyo|Professor Emeritus, Daegu University"] }, { "role": "Panel", "members": ["Masakatsu Horikoshi|Deputy Mayor, Shibukawa City|jp", "Yoon Min-ho|JCIF", "Eom Chan-yong|CEO, Trip Supporters", "Kim Dae-kwon|Mayor of Suseong-gu"] } ] } },
        { "time": "11:45-13:00", "kor": { "title": "오찬", "who": [] }, "eng": { "title": "Luncheon", "who": [] } },
        { "sec": true, "kor": { "title": "Track 2 · DIMF 20주년 기념 세션: K-뮤지컬의 미래" }, "eng": { "title": "Track 2 · DIMF 20th Anniversary Session" } },
        { "time": "13:20-13:30", "kor": { "title": "축하공연", "who": [ { "role": "공연", "members": ["한은빈|뮤지컬배우"] } ] }, "eng": { "title": "Celebratory Performance", "who": [ { "role": "Performance", "members": ["Han Eun-bin|Musical Actor"] } ] } },
        { "time": "13:30-13:45", "kor": { "title": "[기조연설] 수상무대 소개", "who": [ { "role": "발표자", "members": ["박윤진|오피스박김 대표"] } ] }, "eng": { "title": "[Keynote] Introducing the Floating Stage", "who": [ { "role": "Speaker", "members": ["Park Yoon-jin|Principal, office PARKKIM"] } ] } },
        { "time": "13:45-14:00", "kor": { "title": "[기조연설] 수상무대와 공연예술의 미래", "who": [ { "role": "발표자", "members": ["배성혁|DIMF 집행위원장"] } ] }, "eng": { "title": "[Keynote] The Floating Stage and the Future of Performing Arts", "who": [ { "role": "Speaker", "members": ["Bae Sung-hyuk|Executive Director, DIMF"] } ] } },
        { "time": "14:00-14:15", "kor": { "title": "[발제] DIMF 20년의 성과와 미래", "who": [ { "role": "발표자", "members": ["원종원|순천향대학교 SCH미디어랩스대학 학장"] } ] }, "eng": { "title": "[Presentation] 20 Years of DIMF: Achievements and Future", "who": [ { "role": "Speaker", "members": ["Won Jong-won|Dean, College of SCH Media Labs, Soonchunhyang Univ."] } ] } },
        { "time": "14:15-14:50", "kor": { "title": "[대담] DIMF 20년 성과와 미래 비전", "who": [ { "role": "모더레이터", "members": ["고희경|홍익대 공연예술대학원 원장"] }, { "role": "패널", "members": ["이성훈|쇼노트 대표", "오동욱|대구정책연구원 사회문화연구실장", "이용민|(사)한국공연예술포럼 운영위원", "원종원|순천향대학교 SCH미디어랩스대학 학장"] } ] }, "eng": { "title": "[Panel] 20 Years of DIMF and Its Future Vision", "who": [ { "role": "Moderator", "members": ["Ko Hee-kyung|Dean, Graduate School of Performing Arts, Hongik Univ."] }, { "role": "Panel", "members": ["Lee Sung-hoon|CEO, SHOWNOTE", "Oh Dong-wook|Daegu Policy Institute", "Lee Yong-min|Korea Performing Arts Forum", "Won Jong-won|Dean, College of SCH Media Labs, Soonchunhyang Univ."] } ] } },
        { "time": "14:50-15:05", "kor": { "title": "[발제] 상하이의 뮤지컬 발전 경로와 한·일과의 비교", "who": [ { "role": "발표자", "members": ["리차드 페이|중국 상하이문화광장 총괄 매니저|cn"] } ] }, "eng": { "title": "[Presentation] Shanghai's Musical Development Path and a Korea-Japan Comparison", "who": [ { "role": "Speaker", "members": ["Richard Fei|General Manager, Shanghai Culture Square|cn"] } ] } },
        { "time": "15:05-16:00", "kor": { "title": "[대담] 세계 뮤지컬 시장의 흐름", "who": [ { "role": "모더레이터", "members": ["고희경|홍익대 공연예술대학원 원장"] }, { "role": "패널", "members": ["르네 노리스|미국 STAND 예술/교육 디렉터|us", "오치 요이치|일본 마쓰야마 봇짱 대표|jp", "이종규|한국뮤지컬협회 이사장", "권은정|글로벌문화교류위원회 위원장", "리차드 페이|중국 상하이문화광장 총괄 매니저|cn"] } ] }, "eng": { "title": "[Panel] Trends in the Global Musical Market", "who": [ { "role": "Moderator", "members": ["Ko Hee-kyung|Dean, Hongik Univ."] }, { "role": "Panel", "members": ["Renne Norris|Artistic & Education Director, STAND|us", "Yoichi Ochi|Botchan Theatre, Matsuyama|jp", "Lee Jong-kyu|Chairman, Korea Musical Theatre Association", "Angela Kwon|Chair, GCC", "Richard Fei|General Manager, Shanghai Culture Square|cn"] } ] } },
        { "sec": true, "kor": { "title": "CLOSING" }, "eng": { "title": "CLOSING" } },
        { "time": "16:00-16:20", "kor": { "title": "로컬 크리에이터 어워드", "who": [] }, "eng": { "title": "Local Creator Award", "who": [] } },
        { "time": "16:20-16:30", "kor": { "title": "폐회", "who": [ { "role": "폐회사", "members": ["송승환|㈜피엠씨프러덕션 예술감독"] } ] }, "eng": { "title": "Closing", "who": [ { "role": "Closing", "members": ["Song Seung-whan|Artistic Director, PMC Production"] } ] } }
      ]
    }
  ],
  "speakers": [
    { "featured": false, "img": "images/speakers/card/lee-jangwoo.webp", "role": "개회사", "roleEng": "Opening", "kor": { "name": "이장우", "title": "세계문화산업포럼 의장" }, "eng": { "name": "Jangwoo Lee", "title": "Chair, WCIF" } },
    { "featured": false, "img": "images/speakers/card/lee-inseon.webp", "role": "축사", "roleEng": "Congratulatory", "kor": { "name": "이인선", "title": "국회의원" }, "eng": { "name": "Inseon Lee", "title": "Member of the National Assembly" } },
    { "featured": false, "img": "images/speakers/card/kim-seungsu.webp", "role": "축사", "roleEng": "Congratulatory", "kor": { "name": "김승수", "title": "국회의원" }, "eng": { "name": "Seungsu Kim", "title": "Member of the National Assembly" } },
    { "featured": false, "img": "images/speakers/card/kang-eunhee.webp", "role": "축사", "roleEng": "Congratulatory", "kor": { "name": "강은희", "title": "대구시교육청 교육감" }, "eng": { "name": "Eunhee Kang", "title": "Superintendent, Daegu Metropolitan Office of Education" } },
    { "featured": false, "img": "images/speakers/card/john-hong.webp", "role": "기조연설", "roleEng": "Keynote", "kor": { "name": "존홍", "title": "서울대학교 건축학과 교수" }, "eng": { "name": "John Sangki Hong", "title": "Professor, Seoul National University Department of Architecture and Architectural Engineering" } },
    { "featured": true, "img": "images/speakers/card/junya-ishigami.webp", "role": "기조발표", "roleEng": "Keynote", "kor": { "name": "이시가미 준야", "title": "준야 이시가미 + 어소시에이트 대표이사" }, "eng": { "name": "Junya Ishigami", "title": "President, junya.ishigami+associates" } },
    { "featured": true, "img": "images/speakers/card/mladen-jadric.webp", "role": "기조발표", "roleEng": "Keynote", "kor": { "name": "믈라덴 야드리치", "title": "야드리치 아르히텍투어 대표 건축가" }, "eng": { "name": "Mladen Jadrić", "title": "Architect, Jadric Architektur" } },
    { "featured": false, "img": "images/speakers/card/kim-youngsub.webp", "role": "발제", "roleEng": "Presentation", "kor": { "name": "김영섭", "title": "(주)김영섭건축문화건축사사무소 대표 건축사" }, "eng": { "name": "Youngsub Kim", "title": "Principal Architect, Kim Young-Sub + Kunchook-Moonhwa Architect Associates" } },
    { "featured": false, "img": "images/speakers/card/kim-honggeun.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "김홍근", "title": "(주)건축사사무소 ADF건축 대표 건축가" }, "eng": { "name": "Honggeun Kim", "title": "Architect, ADF Architects" } },
    { "featured": false, "img": "images/speakers/card/jun-inkun.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "전인건", "title": "간송미술관 관장" }, "eng": { "name": "Ingeon Jeon", "title": "Director, Kansong Art Museum" } },
    { "featured": true, "img": "images/speakers/card/ryu-jaehyun.webp", "role": "기조연설", "roleEng": "Keynote", "kor": { "name": "류재현", "title": "2026 세계문화유산축전 가야고분군 총감독" }, "eng": { "name": "Jaehyun Ryu", "title": "Artistic Director, 2026 World Heritage Festival, Gaya Tumuli" } },
    { "featured": false, "img": "images/speakers/card/suh-byungki.webp", "role": "모더레이터", "roleEng": "Moderator", "kor": { "name": "서병기", "title": "대중문화평론가" }, "eng": { "name": "Byungkee Suh", "title": "Pop Culture Critic" } },
    { "featured": true, "img": "images/speakers/card/noh-heeyoung.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "노희영", "title": "히노컨설팅펌 대표이사" }, "eng": { "name": "Heeyoung Noh", "title": "CEO, Hino Consulting Firm" } },
    { "featured": false, "img": "images/speakers/card/yu-jungsu.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "유정수", "title": "글로우서울 대표이사" }, "eng": { "name": "Jeongsu Ryu", "title": "CEO, GLOWSEOUL" } },
    { "featured": false, "img": "images/speakers/card/lee-jungwoo.webp", "role": "모더레이터", "roleEng": "Moderator", "kor": { "name": "이정우", "title": "(주)써클커넥션 대표이사" }, "eng": { "name": "Jungwoo Lee", "title": "CEO, Circle Connection, Inc" } },
    { "featured": false, "img": "images/speakers/card/choi-wonseok.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "최원석", "title": "프로젝트렌트 대표이사" }, "eng": { "name": "Wonseok Choi", "title": "CEO, PROJECT RENT" } },
    { "featured": true, "img": "images/speakers/card/baek-aram.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "백아람", "title": "누리하우스(주) 대표이사" }, "eng": { "name": "Aram Baek", "title": "CEO, Nurihaus Inc." } },
    { "featured": false, "img": "images/speakers/card/hong-joosuk.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "홍주석", "title": "어반플레이 대표이사" }, "eng": { "name": "Jooseok Hong", "title": "CEO, URBANPLAY" } },
    { "featured": true, "img": "images/speakers/card/lee-sooman.webp", "role": "WCIF AWARD", "roleEng": "WCIF Award", "kor": { "name": "이수만", "title": "A20엔터테인먼트 키 프로듀서" }, "eng": { "name": "Sooman Lee", "title": "Key Producer, A2O Entertainment" } },
    { "featured": false, "img": "images/speakers/card/kim-daegwon.webp", "role": "환영사", "roleEng": "Welcome", "kor": { "name": "김대권", "title": "대구광역시 수성구청장" }, "eng": { "name": "Daegwon Kim", "title": "Mayor of Suseong-gu, Suseong-gu District, Daegu" } },
    { "featured": false, "img": "images/speakers/card/joo-hoyoung.webp", "role": "축사", "roleEng": "Congratulatory", "kor": { "name": "주호영", "title": "국회의원(전 한일의원연맹 회장)" }, "eng": { "name": "Joo Hoyoung", "title": "Member of the National Assembly (Former Chairman, Korea-Japan Parliamentarians' Union)" } },
    { "featured": false, "img": "images/speakers/card/yuko-obuchi.webp", "role": "축사", "roleEng": "Congratulatory", "kor": { "name": "오부치 유코", "title": "일본 국회 중의원" }, "eng": { "name": "Yuko Obuchi", "title": "Member of the House of Representatives, The House of Representatives, National Diet of Japan" } },
    { "featured": false, "img": "images/speakers/card/kim-sanghyup.webp", "role": "기조연설", "roleEng": "Keynote", "kor": { "name": "김상협", "title": "글로벌녹색성장기구 사무총장" }, "eng": { "name": "Sanghyup Kim", "title": "Executive Director, Global Green Growth Institute" } },
    { "featured": false, "img": "images/speakers/card/horikoshi.webp", "role": "초청연설", "roleEng": "Invited Speech", "kor": { "name": "호리코시 마사카츠", "title": "시부카와시 부시장" }, "eng": { "name": "Masakatsu Horikoshi", "title": "Deputy Mayor, Shibukawa City" } },
    { "featured": false, "img": "images/speakers/card/seo-minkyo.webp", "role": "모더레이터", "roleEng": "Moderator", "kor": { "name": "서민교", "title": "대구대학교 명예교수" }, "eng": { "name": "Minkyo Seo", "title": "Professor Emeritus, Daegu University" } },
    { "featured": false, "img": "images/speakers/card/yoon-minho.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "윤민호", "title": "일본국제금융정보센터 특임연구위원실장" }, "eng": { "name": "Minho Yoon", "title": "Head of Special Research Fellow Office, JCIF" } },
    { "featured": false, "img": "images/speakers/card/eom-chanyong.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "엄찬용", "title": "트립서포터즈 대표이사" }, "eng": { "name": "Chanyong Eom", "title": "CEO, TRIPSUPPORTERS" } },
    { "featured": false, "img": "images/speakers/card/park-yoonjin.webp", "role": "기조연설", "roleEng": "Keynote", "kor": { "name": "박윤진", "title": "오피스박김 대표" }, "eng": { "name": "Yoonjin Park", "title": "President, office PARKKIM" } },
    { "featured": false, "img": "images/speakers/card/bae-sunghyuk.webp", "role": "기조연설", "roleEng": "Keynote", "kor": { "name": "배성혁", "title": "DIMF 집행위원장" }, "eng": { "name": "Sunghuck Bae", "title": "Executive Director, DIMF" } },
    { "featured": false, "img": "images/speakers/card/won-jongwon.webp", "role": "발제", "roleEng": "Presentation", "kor": { "name": "원종원", "title": "순천향대학교 SCH미디어랩스대학 학장" }, "eng": { "name": "Jongwon Won", "title": "Dean, College of SCH Media Labs, Soonchunhyang University" } },
    { "featured": false, "img": "images/speakers/card/ko-heekyung.webp", "role": "모더레이터", "roleEng": "Moderator", "kor": { "name": "고희경", "title": "홍익대학교 공연예술대학원 원장" }, "eng": { "name": "Heekyung Ko", "title": "Dean, Hongik Univ Graduate School of Performing Arts" } },
    { "featured": false, "img": "images/speakers/card/lee-sunghoon.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "이성훈", "title": "쇼노트 대표" }, "eng": { "name": "Seonghoon Lee", "title": "CEO, ShowNote" } },
    { "featured": false, "img": "images/speakers/card/oh-dongwook.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "오동욱", "title": "대구정책연구원 사회문화연구실 실장" }, "eng": { "name": "Dongwook Oh", "title": "Director, Daegu Policy Institute" } },
    { "featured": false, "img": "images/speakers/card/lee-yongmin.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "이용민", "title": "(사)한국공연예술포럼 운영위원" }, "eng": { "name": "Yongmin Lee", "title": "Steering Committee Member, Korea Performing Arts Forum" } },
    { "featured": false, "img": "images/speakers/card/richard-fei.webp", "role": "발제", "roleEng": "Presentation", "kor": { "name": "리차드 페이", "title": "중국 상하이문화광장 총괄 매니저" }, "eng": { "name": "Richard Fei", "title": "General Manager, Shanghai Culture Square Theatre Management Co., Ltd" } },
    { "featured": false, "img": "images/speakers/card/renne-norris.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "르네 노리스", "title": "스텐드 퍼포밍 아츠 예술 및 교육 디렉터" }, "eng": { "name": "Renne Norris", "title": "Artistic & Education Director, STAND Performing Arts" } },
    { "featured": false, "img": "images/speakers/card/yoichi-ochi.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "오치 요이치", "title": "붓짱극장 대표이사" }, "eng": { "name": "Yoichi Ochi", "title": "Representative Director, Botchan Theatre" } },
    { "featured": false, "img": "images/speakers/card/lee-jongkyu.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "이종규", "title": "한국뮤지컬협회 이사장" }, "eng": { "name": "Jongkyu Lee", "title": "President, Korea Musical Theatre Association" } },
    { "featured": false, "img": "images/speakers/card/angela-kwon.webp", "role": "대담 패널", "roleEng": "Panel", "kor": { "name": "권은정", "title": "글로벌문화교류위원회 위원장" }, "eng": { "name": "Angella Kwon", "title": "Chair, Global Cultural exchange Committee(GCC)" } },
    { "featured": false, "img": "images/speakers/card/song-seungwhan.webp", "role": "폐회", "roleEng": "Closing", "kor": { "name": "송승환", "title": "(주)피엠씨프러덕션 예술감독" }, "eng": { "name": "Seunghwan Song", "title": "Artistic director, PMC Production" } },
    { "featured": false, "img": "images/speakers/card/park-changsik.webp", "role": "축사", "roleEng": "Congratulatory", "kor": { "name": "박창식", "title": "한국국제문화교류진흥원 원장 (전 제19대 국회의원)" }, "eng": { "name": "Changsik Park", "title": "President, KOFICE (Former Member of the 19th National Assembly)" } }
  ],
  "futureStage": [
    { "featured": false, "img": "images/speakers/card/park-hanjin.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "박한진", "title": "다보탑레코즈 대표" }, "eng": { "name": "Han Jin Park", "title": "CEO, Dabotap Records" } },
    { "featured": false, "img": "images/speakers/card/kim-miso.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "김미소", "title": "DMZ 피스트레인 뮤직 페스티벌 총감독" }, "eng": { "name": "Miso Kim", "title": "Executive Director, DMZ Peace Train Music Festival" } },
    { "featured": false, "img": "images/speakers/card/jin-sol.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "진솔", "title": "스타일대디 대표" }, "eng": { "name": "Jin Sol", "title": "CEO, Style Daddy" } },
    { "featured": false, "img": "images/speakers/card/kim-kyunghoon.webp", "role": "호스트", "roleEng": "Host", "kor": { "name": "김경훈", "title": "더블유더블유이엔티 MC" }, "eng": { "name": "Kyung Hun Kim", "title": "MC, WWENT" } },
    { "featured": false, "img": "images/speakers/card/gwak-jaewon.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "곽재원", "title": "트래쉬버스터즈 대표" }, "eng": { "name": "Jae Won Gwak", "title": "CEO, Trash Busters" } },
    { "featured": false, "img": "images/speakers/card/jang-eunseok.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "장은석", "title": "수무 대표" }, "eng": { "name": "Eunserk Chang", "title": "Principal Designer, SUMU" } },
    { "featured": false, "img": "images/speakers/card/choi-jaesik.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "최재식", "title": "로우리트콜렉티브 대표" }, "eng": { "name": "Jae Sik Choi", "title": "CEO, Lowlit Collective" } },
    { "featured": false, "img": "images/speakers/card/jung-juhee.webp", "role": "호스트", "roleEng": "Host", "kor": { "name": "정주희", "title": "프리랜서 기후캐스터" }, "eng": { "name": "Juhee Jung", "title": "Freelance Climate Caster" } },
    { "featured": false, "img": "images/speakers/card/lee-boyoung.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "이보영", "title": "워크모어 운영총괄" }, "eng": { "name": "Boyoung Lee", "title": "COO, WORKMORE" } },
    { "featured": false, "img": "images/speakers/card/agon.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "아곤", "title": "포뮬라랩스 대표" }, "eng": { "name": "Agon", "title": "CEO, Formula Labs" } },
    { "featured": false, "img": "images/speakers/card/park-jinhyun.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "박진현", "title": "계원예술대학교 시각디자인학과 교수" }, "eng": { "name": "Jinhyun Park", "title": "Professor, Visual Communication Design, Kaywon University of Art & Design" } },
    { "featured": false, "img": "images/speakers/card/lee-jungwoo-fs.webp", "role": "호스트", "roleEng": "Host", "kor": { "name": "이정우", "title": "(주)써클커넥션 대표이사" }, "eng": { "name": "Nathan Lee", "title": "CEO, Circle Connection" } },
    { "featured": false, "img": "images/speakers/card/an-jisung.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "안지성", "title": "주식회사 악수 대표" }, "eng": { "name": "Jisung An", "title": "CEO, AXOO" } },
    { "featured": false, "img": "images/speakers/card/choi-yerim.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "최예림", "title": "도슨트" }, "eng": { "name": "Yerim Choi", "title": "Docent" } },
    { "featured": false, "img": "images/speakers/card/kim-jungmin.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "김정민", "title": "스튜디오 콩테 대표" }, "eng": { "name": "Jungmin Kim", "title": "CEO, Studio Conte" } },
    { "featured": false, "img": "images/speakers/card/kim-yura.webp", "role": "호스트", "roleEng": "Host", "kor": { "name": "김유라", "title": "웨이비즘 코미디자이너" }, "eng": { "name": "Yura Kim", "title": "Designer, wavismm" } },
    { "featured": false, "img": "images/speakers/card/yeo-intaek.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "여인택", "title": "피치스그룹코리아 파운더" }, "eng": { "name": "In Taek Yeo", "title": "Founder, Peaches Group Korea" } },
    { "featured": false, "img": "images/speakers/card/jung-inmo.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "정인모", "title": "주식회사 사사사 대표" }, "eng": { "name": "Inmo Chung", "title": "CEO, SASASA Inc" } },
    { "featured": false, "img": "images/speakers/card/jung-minkyu.webp", "role": "패널", "roleEng": "Panel", "kor": { "name": "정민규", "title": "하이어코퍼레이션 부사장" }, "eng": { "name": "Minkyu Jeong", "title": "Vice President, Higher Corporation" } },
    { "featured": false, "img": "images/speakers/card/heo-yurim.webp", "role": "호스트", "roleEng": "Host", "kor": { "name": "허유림", "title": "아이즈 매거진 편집장" }, "eng": { "name": "Yurim Heu", "title": "Editor in Chief, eyesmag" } }
  ],
  "futureStageProgram": [
    { "no": 1, "time": "14:15-14:55", "cat": "Entertainment", "kor": "초연결 시대의 엔터테인먼트: 팬덤, 페스티벌, 그리고 소셜 네트워크", "eng": "Entertainment in the Hyper-Connected Era: Fandom, Festivals, and Social Networks", "host": "김경훈", "panel": ["박한진", "김미소", "진솔"] },
    { "no": 2, "time": "14:55-15:35", "cat": "ESG", "kor": "지속가능한 멋(Sustainable Chic): 환경, 디자인과 라이프스타일이 되다", "eng": "Sustainable Chic: When the Environment Becomes Design and Lifestyle", "host": "정주희", "panel": ["곽재원", "최재식", "장은석"] },
    { "no": 3, "time": "15:45-16:25", "cat": "Tech", "kor": "Tech for Creators: 기술이 재정의하는 미래의 일과 창작 생태계", "eng": "Tech for Creators: Technology Redefining the Future of Work and Creation", "host": "이정우", "panel": ["이보영", "아곤", "박진현"] },
    { "no": 4, "time": "16:25-17:05", "cat": "Art", "kor": "예술의 일상화: 시각, 공간, 스토리텔링으로 문턱을 넘은 아트 씬", "eng": "Art in Everyday Life: An Art Scene Beyond the Threshold through Vision, Space, and Storytelling", "host": "김유라", "panel": ["안지성", "최예림", "김정민"] },
    { "no": 5, "time": "17:05-17:45", "cat": "Life Style", "kor": "Subculture to Mainstream: 마이너한 취향이 거대한 비즈니스가 될 때", "eng": "Subculture to Mainstream: When Niche Tastes Become Big Business", "host": "허유림", "panel": ["여인택", "정인모", "정민규"] }
  ],
  "bios": {
    "이인선": { "kor": "21대, 22대 국회의원", "eng": "Member of the 21st and 22nd National Assembly", "links": [] },
    "김승수": { "kor": "21대, 22대 국회의원", "eng": "Member of the 21st and 22nd National Assembly", "links": [] },
    "김경훈": { "kor": "MC 훈'으로 활동하는 사회자다. 다양한 축제와 브랜드 행사의 사회를 맡아 현장의 분위기를 이끈다.", "eng": "Host and presenter active as \"MC Hoon.\" He leads the atmosphere on-site by hosting various festivals and brand events.", "links": [] },
    "김미소": { "kor": "DMZ 피스트레인의 총감독이다. 철원에서 음악으로 경계를 허물고, '함께 춤추는' 평화와 공존의 축제 감각을 이어간다.", "eng": "Executive Director of DMZ Peace Train Music Festival. She breaks down borders through music in Cheorwon, continuing the festive spirit of peace and coexistence through \"dancing together.\"", "links": [] },
    "진솔": { "kor": "스타일대디의 대표이사다. 인플루언서 및 1인 미디어 분야의 연쇄 창업가로서 뉴미디어 크리에이터 생태계의 성장을 주도한다.", "eng": "He is the CEO of Style Daddy. As a serial entrepreneur in the new media and influencer industries, he leads the growth of the creator ecosystem.", "links": [] },
    "박진현": { "kor": "계원예술대학교 시각디자인과 교수다. UX 디자인 교육에 전문 코칭 기법을 접목해 차세대 디자인 인재의 혁신과 성장을 이끈다.", "eng": "He is a professor of Visual Communication Design at Kaywon University of Art and Design. He drives the innovation and growth of next-generation design talents by integrating professional coaching methodologies into UX design education.", "links": [] },
    "김정민": { "kor": "가드닝 스튜디오 콩테의 대표다. 식물을 드로잉 도구 삼아 공간에 강렬하고 자유로운 식물 예술을 그려낸다.", "eng": "He/She is the CEO of Gardening Studio Conté. Using plants as drawing tools, he/she paints bold and free-spirited botanical art within spaces.", "links": [] },
    "정주희": { "kor": "전직 기상캐스터이자 그린 인플루언서다. 일상 속 기후위기 대응과 친환경 실천 방안을 대중에게 알린다.", "eng": "Former weather caster and green influencer. She raises public awareness about responding to the climate crisis and practicing eco-friendly habits in daily life.", "links": [] },
    "곽재원": { "kor": "다회용기 대여 서비스를 제공하는 트래쉬버스터즈의 창업가다. 축제와 기업 등 일상 속 일회용품 쓰레기 문제를 실질적으로 해결한다.", "eng": "Founder of Trash Busters, a multi-use container rental service. He provides practical solutions to single-use waste issues in everyday life, festivals, and corporate environments.", "links": [] },
    "최재식": { "kor": "업사이클링 디자인 스튜디오 로우리트콜렉티브의 대표다. 버려진 것들에서 가치를 발굴하고 새로운 목적을 지닌 라이프스타일 제품을 선보인다.", "eng": "He is the CEO of Lowlit Collective, an upcycling design studio. By discovering value in discarded materials, he presents lifestyle products with a renewed purpose.", "links": [] },
    "이보영": { "kor": "커뮤니티 기반 업무 공간인 워크모어의 공동창업자다. 창업가와 빌더를 위한 네트워킹과 프로젝트를 기획하며 새로운 창업 생태계를 구축한다.", "eng": "Co-founder of Workmore, a community-based workspace. She builds a new entrepreneurial ecosystem by planning networking events and projects for entrepreneurs and builders.", "links": [] },
    "아곤": { "kor": "웹3 마케팅 에이전시 포뮬라랩스의 대표다. 해외 콘텐츠와 IP가 한국 시장에 안착하도록 커뮤니티, PR, 이벤트를 아우르는 통합 마케팅을 설계한다.", "eng": "CEO of Formula Labs, a Web3 marketing agency. He designs integrated marketing strategies encompassing community building, PR, and events to help international content and IPs successfully enter the Korean market.", "links": [] },
    "김유라": { "kor": "디자이너이자 크리에이터이다. 독창적인 감성과 디렉팅을 바탕으로 신선한 시각적 트렌드를 세상에 선보이고 있다.", "eng": "Designer and creator. Based on her original sensibility and directing, she introduces fresh visual trends to the world.", "links": [] },
    "안지성": { "kor": "글로벌 아트 컴퍼니 악수(AXOO)의 대표다. 비주얼 아티스트와 글로벌 브랜드를 연결해 다양한 아트 컬래버레이션 프로젝트를 총괄한다.", "eng": "CEO of AXOO, a global art agency. He directs art collaborations, including exhibitions and events, by connecting visual artists with global brands.", "links": [] },
    "최예림": { "kor": "미술 전시를 ‘깊이 있고’ 유쾌하게 풀어내는 도슨트이자 크리에이터다. 다양한 온라인 플랫폼을 활용해 대중의 예술적 시야를 넓힌다.", "eng": "Docent and creator who interprets art exhibitions in an entertaining way. She broadens the public's artistic horizons through various online platforms.", "links": [] },
    "장은석": { "kor": "디자인 스튜디오 수무의 대표다. 조경을 기반으로 미디어 아트, 사운드 등 다양한 감각을 결합해 자연이 주는 안식을 공간에 담아낸다.", "eng": "He is the CEO of Design Studio Sumu. Blending landscape architecture with diverse sensory elements like media art and sound, he infuses spaces with the comfort of nature.", "links": [] },
    "허유림": { "kor": "트렌드 매체 아이즈매거진의 편집이다. 패션과 문화 전반을 아우르는 날카로운 큐레이션으로 동시대 라이프스타일의 이정표를 제시한다.", "eng": "Editor of eyesmag, a trend media outlet. She presents milestones for contemporary lifestyles through sharp curation encompassing fashion and culture.", "links": [] },
    "여인택": { "kor": "라이프스타일 브랜드 피치스의 대표다. 자동차 튜닝에 패션과 음악, 영상 콘텐츠를 결합해 마니아층을 사로잡는 독창적인 자동차 문화를 이끈다.", "eng": "CEO of Peaches., a lifestyle brand. He leads a unique car culture that captivates enthusiasts by combining car tuning with fashion, music, and video content.", "links": [] },
    "정인모": { "kor": "사우나 문화 브랜드 사사사의 창업자이자 대표이다. 축제 팝업과 커뮤니티를 중심으로 사우나에 대한 진심을 독창적인 문화 콘텐츠로 풀어낸다.", "eng": "Founder and CEO of SASASA, a sauna culture brand. Focusing on festival pop-ups and communities, he translates his passion for sauna culture into unique cultural content.", "links": [] },
    "정민규": { "kor": "미용의료 기업 하이어코퍼레이션의 부사장이다. 메디컬 뷰티를 일상 속 라이프스타일 영역으로 확장하며 글로벌 스킨부스터 사업과 메디컬 플랫폼을 총괄한다.", "eng": "Vice President of Higher Corporation, a medical aesthetic company. He expands medical beauty into an everyday lifestyle domain, overseeing the global skin booster business and medical platforms.", "links": [] },
    "이수만": { "kor": "SM엔터테인먼트를 설립해 H.O.T.부터 에스파에 이르는 스타들을 배출하며 K-pop 프로듀싱 시스템의 표준을 만든 프로듀서다. 현재는 글로벌 아티스트 육성을 위해 설립한 A2O엔터테인먼트의 키 프로듀서로 활동하며 '넥스트 한류'를 이끌고 있다. 세계문화산업포럼(WCIF)에는 제1회부터 기조연설자로 참여해 왔다.", "eng": "Lee Soo-man founded SM Entertainment and built the production system that shaped the K-pop industry, launching stars from H.O.T. to aespa. He now serves as Key Producer of A2O Entertainment and has delivered keynote speeches at WCIF since its first edition.", "links": [{"title": "이수만, K팝 넘어 세계로 'A2O엔터' (이코노믹데일리)", "url": "https://www.economidaily.com/view/20250203082205660"}, {"title": "제1회 세계문화산업포럼 기조연설 (아시아투데이)", "url": "https://www.asiatoday.co.kr/view.php?key=20201028010016929"}] },
    "존홍": { "kor": "서울대학교 건축학과 교수이자 건축가다. 디자인 랩 프로젝트 아키텍처를 이끌며 건축과 도시학을 융합하는 작업을 펼치고 있다. AIA 어워드 18회 수상 등 다수의 국제 건축상을 받았으며 베니스 비엔날레를 비롯한 주요 행사에 작품을 전시했다. 서울도시건축비엔날레 큐레이터 및 유력 매체의 건축 비평가로도 활약했다. 부임 전 하버드 GSD 부교수를 역임했으며, 동 대학원 석사와 버지니아 대학교 학사를 우등으로 취득했다.", "eng": "Architect and Professor of Architecture at Seoul National University. He leads the design lab Project: Architecture, integrating architecture and urbanism. His internationally acclaimed works have won 18 AIA Awards and been exhibited at the Venice Biennale. He has also served as a curator for the Seoul Biennale of Architecture and Urbanism and is an active architectural critic. Previously an Associate Professor at Harvard GSD, he holds a Master’s from Harvard GSD and a Bachelor’s from the University of Virginia, both with honors.", "links": [{"title": "서울대학교 건축학과 프로필", "url": "https://architecture.snu.ac.kr/people/john-hong/"}] },
    "이시가미 준야": { "kor": "도쿄예술대학을 거쳐 준야 이시가미+어소시에이츠를 설립한 일본의 거장 건축가다. 자연과 건축의 경계를 허무는 철학으로 베니스비엔날레 황금사자상을 수상했으며, 프리더릭 키슬러 상과 아놀드 브루너 기념상 등을 휩쓸며 세계 건축계를 선도하고 있다.", "eng": "A master Japanese architect who founded junya.ishigami+associates after studying at Tokyo University of the Arts. Renowned for blurring the boundaries between nature and architecture, he won the Venice Biennale Golden Lion. His global acclaim continues with prestigious honors including the Frederick Kiesler Prize and the Arnold W. Brunner Memorial Prize.", "links": [{"title": "이시가미 준야: 중력, 자연, 빛 (SPACE)", "url": "https://vmspace.com/report/report_view.html?base_seq=Mjcz"}] },
    "믈라덴 야드리치": { "kor": "야드리치 아르히텍투어의 대표이자 빈 공과대학교 건축·계획학부 교수로 활동하는 오스트리아 건축가다. 오스트리아 예술가 협회인 쿤스트러하우스 건축 부문 회장을 맡고 있으며, 한국에서는 부산시장상 수상 및 서울시립 사진미술관을 설계하는 등 글로벌 무대에서 혁신적인 도시 프로젝트를 이끌고 있다.", "eng": "Founder of Jadric Architektur and Professor of Architecture and Planning at TU Wien. He serves as the President of the Architecture Section at Künstlerhaus, Austria's oldest artists' association. He leads innovative urban projects globally, with prominent works in Korea including the design of the Seoul Photographic Art Museum.", "links": [{"title": "JADRIC ARCHITEKTUR (브리크매거진)", "url": "https://magazine.brique.co/brq-architects/jadric-architektur/"}] },
    "김영섭": { "kor": "김영섭 건축문화 대표이자 성균관대학교 석좌교수를 역임한 건축가다. 한강르네상스 마스터플래너와 초대 국가건축정책위원회 위원을 지냈으며, '세계 건축가 1000인'에 등재되는 등 문화와 공공 디자인을 융합한 도시 발전을 선도해 왔다.", "eng": "Representative of Kim Young-sub Architecture Culture and former Chair Professor at Sungkyunkwan University. He served as the Master Planner for the Han River Renaissance and is listed among the \"1000 World Architects,\" recognized for leading urban development that fuses culture with public design.", "links": [] },
    "김홍근": { "kor": "건축사사무소 ADF건축의 대표건축가다. 대구광역시 신청사 건립 설계공모운영위원회 위원장을 역임했으며, 경주 APEC 경제전시장과 아트피아수성 리모델링 등 주요 공공 및 문화 공간을 설계했다. 대구건축 국제비엔날레에서 대구광역시장상을 3회 수상하는 등 지역 도시 디자인 발전에 기여해 왔다.", "eng": "Principal Architect of ADF Architects. He served as the Chairperson of the Design Competition Steering Committee for the Daegu Metropolitan City Hall and has designed major public and cultural spaces, including the Gyeongju APEC Economic Exhibition Hall and the Suseong Artpia renovation. He is also a three-time recipient of the Mayor of Daegu Award at the Daegu International Architecture Biennale.", "links": [] },
    "전인건": { "kor": "간송미술관 및 대구간송미술관 관장이자 헤리티지 아트 대표이사다. '문화보국'의 정신을 계승하며 VR과 미디어아트 등 신기술을 접목한 전시를 통해 고미술의 새로운 향유 방식을 제시하고, 대구간송미술관 개관을 통해 간송의 문화유산을 지역과 세대를 넘어 확장하는 데 앞장서고 있다.", "eng": "Director of the Gansong Art Museum and Daegu Gansong Art Museum, and CEO of Heritage Art. Inheriting the spirit of protecting the nation through culture, he presents new ways to appreciate traditional art by integrating advanced technologies like VR and media art. He expands the reach of Gansong's cultural heritage across regions and generations, notably through the opening of the Daegu Gansong Art Museum.", "links": [{"title": "\"문화유산에 스토리와 감정 전달해야\" (이데일리)", "url": "https://www.edaily.co.kr/News/Read?newsId=03381686642235504&mediaCodeNo=257"}] },
    "류재현": { "kor": "세계문화유산축전 가야고분군 총감독으로 활동 중인 문화기획자다. 클럽데이, 월드DJ페스티벌, 대한민국 밤밤페스타 등을 이끌었으며, '같은 것은 하지 않는다'는 철학 아래 고정관념을 깨고 늘 새로운 형식의 축제와 문화 콘텐츠를 선보여 왔다.", "eng": "He is a cultural planner currently serving as the General Director of the Gaya Tombs Festival, 2026 World Cultural Heritage Festival. He has led major events such as Club Day, World DJ Festival, and Korea Bam Bam Festa. Under the philosophy of \"never doing the same thing,\" he has consistently broken stereotypes to introduce innovative formats for festivals and cultural content.", "links": [{"title": "매번 '처음'을 만드는 문화기획자 (디자인정글)", "url": "https://www.jungle.co.kr/magazine/206855"}] },
    "서병기": { "kor": "대중문화평론가이자 아이뉴스24 대중문화선임기자다. 서울신문과 헤럴드경제를 거치며 오랜 기간 대중문화 현장을 취재해 왔으며, 다양한 칼럼과 저서를 통해 K-팝 및 방송·연예 트렌드를 분석하고 있다. 저서로 『방탄소년단과 K팝』, 『임영웅의 힘』 등이 있다.", "eng": "A pop culture critic and Senior Pop Culture Journalist at iNews24. Having covered the entertainment scene at Seoul Shinmun and Herald Economy, he analyzes K-pop and media trends through columns and publications, including BTS and K-Pop and The Power of Lim Young-woong.", "links": [{"title": "서병기의 문화와 역사 (헤럴드경제 연재)", "url": "https://biz.heraldcorp.com/series/108"}] },
    "노희영": { "kor": "히노컨설팅펌 대표이자 푸드 및 라이프스타일 브랜드 기획자다. 오리온그룹 부사장, CJ그룹 브랜드전략 고문 등을 역임하며 마켓오, 비비고 등 다수의 브랜드를 기획했다. 최근 동계올림픽 코리아하우스 단장, 서울도시건축비엔날레 마케팅 디렉터 등을 맡아 글로벌 무대에서 K-컬처 브랜딩을 이끌고 있다.", "eng": "CEO of Hino Consulting Firm and a brand planner specializing in the food and lifestyle sectors. She previously served as Vice President of Orion Group and Brand Strategy Advisor for CJ Group, launching renowned brands like Market O and Bibigo. She continues to lead K-culture branding globally, recently serving as the Director of Korea House for the Winter Olympics and Marketing Director for the Seoul Biennale of Architecture and Urbanism.", "links": [{"title": "노희영 식음연구소 대표 인터뷰 (아주경제)", "url": "https://www.ajunews.com/view/20200527140843642"}] },
    "유정수": { "kor": "공간 기획 기업 글로우서울의 대표이사다. 익선동과 창신동 등에서 '청수당', '온천집' 등의 공간을 기획하며 지역에 맞는 도시재생 프로젝트를 이끌었다. 신세계와 롯데 등 대형 상업시설의 특화설계를 총괄하며 뉴욕 등 글로벌 진출을 추진하고 있으며, SBS 방송 '동네멋집'의 MC로도 활동하고 있다.", "eng": "CEO of the space planning company Glow Seoul. He has led tailored urban regeneration projects in areas like Ikseon-dong and Changsin-dong, creating notable spaces such as Cheongsudang and Oncheonjip. He oversees specialized designs for major commercial facilities like Shinsegae and Lotte, drives global expansion including in New York, and serves as the MC for the SBS program \"Dongne Meotjip\".", "links": [{"title": "GLOW SEOUL 공식 사이트", "url": "https://glowseoul.co.kr/"}] },
    "이정우": { "kor": "(주)써클커넥션의 창업자이자 대표이사. 한국외대 경영학과, 핀란드 알토대학교 MBA 를 수학하였으며, 이벤트 디렉터로 활동하고 있다.", "eng": "Founder and CEO of Circle Connection Co., Ltd. He studied Business Administration at Hankuk University of Foreign Studies, earned an MBA from Aalto University in Finland, and currently works as an event director.", "links": [{"title": "씨클커넥션 이정우 대표 인터뷰 (전자신문)", "url": "https://www.etnews.com/201302040351"}] },
    "박한진": { "kor": "대한민국을 대표하는 디제이이자 프로듀서이다. 클럽 및 페스티벌을 비롯,무용, 광고, 게임 등 다양한 영역에서 활동중이며 기존 디제이의 한계를 넘어선 다양한 길을 개척하고 있는 선구자중 한명이다.", "eng": "One of South Korea's leading DJs and producers, active across diverse fields including clubs, festivals, dance, advertising, and gaming. He is a pioneer blazing new trails that transcend the boundaries of conventional DJing.", "links": [] },
    "백아람": { "kor": "대한민국의 벤처 창업가다. Wishcompany의 공동창업자 출신으로, 2020년 누리하우스를 설립했다. K-뷰티 산업에서의 경험을 바탕으로 현재는 AI 기반 크리에이터 플랫폼 '누리라운지'를 통해 글로벌 인프라를 구축하고 있으며, 포브스에 소개된 바 있다. 서울과 뉴욕을 거점으로 활동 중이다.", "eng": "He is a venture entrepreneur in South Korea. A co-founder of Wishcompany, he founded Nurihaus in 2020. Drawing on his experience in the K-beauty industry, he now operates Nurilounge, an AI-powered platform building a global creator infrastructure. Featured in Forbes, he is active with bases in Seoul and New York.", "links": [{"title": "백아람 누리하우스 대표 (뉴스1)", "url": "https://www.news1.kr/industry/distribution/5890525"}] },
    "홍주석": { "kor": "도시콘텐츠 전문기업 어반플레이의 대표이자 사단법인 로컬브랜드포럼(LBF) 이사장이다. '연남장', '연남방앗간' 등 동네의 유·무형 콘텐츠를 발굴해 오프라인 공간과 서비스로 선보이는 로컬 비즈니스를 이끌고 있다. 현재 지방시대위원회 전문위원으로 활동 중이며, 일자리 창출 유공으로 대통령 표창을 수상했다.", "eng": "CEO of the urban content company URBANPLAY and Chairman of the Local Brand Forum (LBF). He leads local creative businesses by discovering neighborhood content and transforming it into spaces and services, such as 'Yeonnamjang' and 'Yeonnam Bangatgan'. He currently serves as an expert member of the Presidential Committee on Local Development and is a recipient of the Presidential Citation.", "links": [{"title": "홍주석 어반플레이 대표 \"로컬은 콘텐츠 실험장\" (더피알)", "url": "https://www.the-pr.co.kr/news/articleView.html?idxno=51609"}] },
    "주호영": { "kor": "대구 수성구갑을 지역구로 둔 6선 국회의원으로, 제22대 국회 전반기 국회부의장을 역임했다. 2024년 한일의원연맹 정기총회에서 만장일치로 회장에 선출돼 한일 의원 외교를 이끌고 있다.", "eng": "Joo Ho-young is a six-term member of the National Assembly representing Suseong-gu, Daegu, former Deputy Speaker, and chairman of the Korea-Japan Parliamentarians' Union since 2024.", "links": [{"title": "주호영, 한일의원연맹 회장 선출 (세명일보)", "url": "https://m.smnews.co.kr/view.php?idx=240456"}] },
    "오부치 유코": { "kor": "일본 자유민주당 소속 중의원 의원(군마현 제5구)으로, 1998년 '김대중-오부치 공동선언'을 통해 미래지향적 한일관계의 토대를 놓은 오부치 게이조 전 총리의 딸이다. 부친의 뜻을 이어 한일 의원 교류와 양국 관계 발전에 힘써 온 대표적인 지한파 정치인으로 꼽힌다.", "eng": "Yuko Obuchi is a member of Japan's House of Representatives and daughter of former Prime Minister Keizo Obuchi, who signed the landmark 1998 Kim Dae-jung-Obuchi Joint Declaration. She is regarded as a leading pro-Korea lawmaker.", "links": [{"title": "오부치 유코 (위키백과)", "url": "https://ko.wikipedia.org/wiki/%EC%98%A4%EB%B6%80%EC%B9%98_%EC%9C%A0%EC%BD%94"}] },
    "김상협": { "kor": "글로벌녹색성장연구소(GGGI) 사무총장이다. 한국인 최초로 취임했으며, 대통령 직속 2050 탄소중립녹색성장위원회 공동위원장, KAIST 부총장, 청와대 녹색성장기획관을 역임했다. 미디어·학계·공공정책 부문을 넘나들며 글로벌 기후 행동과 지속가능발전 의제를 이끌어왔다.", "eng": "Executive Director of the Global Green Growth Institute (GGGI), serving as the first Korean national in this role. He previously served as Co-Chairperson of the Presidential Commission on 2050 Carbon Neutrality and Green Growth, Vice-President of KAIST, and Senior Secretary to the President for Green Growth, leading global climate action and sustainable development.", "links": [{"title": "김상협, GGGI 사무총장 임명 (정책브리핑)", "url": "https://www.korea.kr/briefing/pressReleaseView.do?newsId=156646824"}] },
    "윤민호": { "kor": "일본의 공익재단법인 일본국제금융정보센터(JCIF) 특임연구위원실장이다. JCIF는 1983년 일본 주요 민간 금융기관들이 설립한 국제금융 전문 조사·연구기관으로, 세계 60여 개국의 거시경제와 국가 리스크를 분석하고 있다.", "eng": "Yoon Min-ho heads the Special Research Fellow Office at the Japan Center for International Finance (JCIF), a Tokyo-based institution analyzing macroeconomic conditions across more than 60 countries.", "links": [{"title": "JCIF 공식 사이트", "url": "https://www.jcif.or.jp/"}] },
    "엄찬용": { "kor": "주식회사 트립서포터즈의 대표이사 겸 창업자다. 하나투어 차세대 플랫폼 구축 PL을 역임한 트래블테크 및 인바운드 관광 플랫폼 전문가다. 현재 AI 기반 외국인 관광객 맞춤형 견적·일정 통합 플랫폼인 'GIPS 2.0'의 총괄 개발 및 PoC를 수행하고 있다.", "eng": "Founder and CEO of Trip Supporters Co., Ltd. He is a travel-tech and inbound tourism platform architecture expert who previously served as a project leader (PL) for Hanatour's next-generation platform. He currently oversees the development and PoC of 'GIPS 2.0', an AI-powered customized itinerary and quoting platform for foreign tourists.", "links": [{"title": "트립서포터즈", "url": "https://www.tripsupporters.com/"}] },
    "박윤진": { "kor": "서울과 보스턴을 기반으로 하는 조경·도시설계 스튜디오 오피스 박김의 대표다. 미국 하버드 대학교 디자인 대학원 설계교수를 역임했다. 서울공예박물관 옥외공간, 광교 신도시 공원녹지체계 마스터플랜, 양화 한강공원 등 다수의 조경 프로젝트를 설계했다. 미국 조경건축가협회(ASLA) 커뮤니케이션 부문 최우수상을 수상했으며, 대구 수성못 수상공연장 국제지명현상에 당선된 바 있다.", "eng": "Founder of PARKKIM, an urban design and landscape architecture studio based in Seoul and Boston. She served as a professor at the Harvard University Graduate School of Design. She has designed major projects including the outdoor space for the Seoul Museum of Craft Art, the Gwanggyo New Town Park Master Plan, and the Yanghwa Han River Park. She won the ASLA Grand Award in Communications and the International Competition for the Suseong Lake Floating Stage in Daegu", "links": [{"title": "박윤진 인터뷰 (환경과조경)", "url": "https://www.youtube.com/watch?v=uQ2ivl3_ENU"}] },
    "배성혁": { "kor": "아시아 최초의 국제뮤지컬페스티벌인 대구국제뮤지컬페스티벌(DIMF)의 집행위원장이자 예술기획 성우 대표다. 2006년 프레 DIMF 공동집행위원장을 시작으로 제2대 및 제5대 집행위원장을 맡아 전 세계 뮤지컬인이 주목하는 축제를 이끌어왔다. 한국뮤지컬협회 이사로도 활동 중이며, 문화체육관광부 장관상을 수상했다. (169자)", "eng": "Executive Director of the Daegu International Musical Festival (DIMF), Asia's first international musical festival, and CEO of Seongwoo Arts Management. He has led the globally recognized festival, serving as the co-executive director of Pre-DIMF and the 2nd and 5th Executive Director of DIMF. He also serves as a board member of the Korea Musical Association and received the Minister of Culture, Sports and Tourism Award.", "links": [{"title": "\"대구 넘어 한국 문화산업의 미래\" 20주년 DIMF (뉴시스)", "url": "https://www.newsis.com/view/NISX20260428_0003609774"}] },
    "원종원": { "kor": "순천향대학교 SCH미디어랩스대학 학장이자 공연영상학과·미디어커뮤니케이션학과 교수다. 언론사 기자 및 특파원을 거친 뮤지컬 평론가로, '오페라의 유령', '캣츠' 등 다수의 작품을 우리말로 번역했다. 현재 한국뮤지컬협회 이사, 한국뮤지컬학회 부회장, 대구국제뮤지컬페스티벌(DIMF) 이사 겸 집행위원을 맡고 있다.", "eng": "Dean of the College of SCH Media Labs and Professor of Performance & Film and Media Communication at Soonchunhyang University. A musical critic with a background as a journalist and foreign correspondent, he has translated hit musicals such as 'The Phantom of the Opera' and 'Cats'. He currently serves as a board member of the Korea Musical Association, Vice President of the Korean Society for Musical Theater Studies, and an executive board member of DIMF.", "links": [{"title": "\"K-뮤지컬에 세계가 열광하는 이유\" (YTN)", "url": "https://www.ytn.co.kr/_ln/0106_202506260057104578"}] },
    "고희경": { "kor": "홍익대학교 공연예술대학원장 겸 대학로아트센터장이며 한국뮤지컬학회 회장이다. 예술의전당 공연기획팀장, 디큐브아트센터 극장장, 서울예술단 이사 등을 역임하며 문화예술 기획 및 극장 운영 전문가로 활동해 왔다. 대한민국 대통령 포장과 서울시 문화상을 수상한 바 있다.", "eng": "Dean of the Graduate School of Performing Arts and Director of the Daehangno Art Center at Hongik University, and President of the Korean Society for Musical Theater Studies. She has built an extensive career in arts management, having served as the head of performance planning at the Seoul Arts Center and theater director of the D-Cube Arts Center. She is a recipient of the Presidential Citation and the Seoul Culture Award.", "links": [{"title": "홍익대학교 공연예술대학원", "url": "http://hipa.hongik.ac.kr/hipa/intro04.html"}] },
    "이성훈": { "kor": "주식회사 쇼노트 대표이사이자 한국뮤지컬협회 부이사장이다. CJ ENM 공연사업본부장 및 중국 법인장을 역임하며 오랜 기간 공연 산업을 이끌어왔다. 홍익대학교 공연예술대학원 겸임교수를 겸임하고 있으며, 최근 롯데컬처웍스와 손잡고 누적 조회수 2억 5,000만 뷰의 웹소설 원작 뮤지컬 '세이렌' 공동 제작에 나서는 등 다채로운 공연 콘텐츠 기획을 주도하고 있다.", "eng": "CEO of Shownote Co., Ltd. and Vice President of the Korea Musical Association. With extensive experience leading the performing arts industry, he previously served as Head of the Performing Arts Division at CJ ENM and CEO of CJ ENM China. Currently an adjunct professor at the Hongik University Graduate School of Performing Arts, he is actively driving content innovation, recently partnering with Lotte Cultureworks to co-produce 'Siren', a musical based on a mega-hit web novel with 250 million views.", "links": [{"title": "쇼노트 공식 홈페이지", "url": "https://www.shownote.com/Main/Index"}] },
    "오동욱": { "kor": "대구정책연구원 사회문화연구실장이자 선임연구위원이다. 문화체육관광부 지역문화협력위원회 위원을 지냈으며, 대구시 문화예술진흥위원회와 축제조직위원회 위원, 한국지역문화학회 이사로 활동 중이다. 한국문화예술법학회 부회장을 역임하는 등 학계와 행정을 넘나들며 지역 문화 정책 수립에 앞장서고 있다.", "eng": "Research Fellow and Director of the Social and Cultural Research Department at the Daegu Policy Institute. He plays a key role in regional cultural policy, having served on the Regional Culture Cooperation Committee under the Ministry of Culture, Sports and Tourism. He currently serves on the Daegu Cultural Arts Promotion Committee and the Daegu Festival Organizing Committee, and is a board member of the Korean Association of Regional Culture.", "links": [{"title": "대구정책연구원", "url": "https://dpi.re.kr/"}] },
    "이용민": { "kor": "사단법인 한국공연예술포럼 운영위원이다. 한국예술종합학교 산학협력단 소속 계촌클래식축제 운영총감독 및 연구원을 겸하고 있다. 과거 통영국제음악재단 대표이사를 역임했으며 현재 아시아태평양공연예술센터연합회 집행위원으로도 활동 중이다. 제60회 대한민국문화예술상에서 대통령표창을 받았다.", "eng": "Steering Committee Member of the Korea Performing Arts Forum. He also serves as a researcher and the General Director of the Gyechon Classic Festival under the Korea National University of Arts Industry-Academic Cooperation Foundation. He previously served as the CEO of the Tongyeong International Music Foundation. He is an Executive Committee Member of the Association of Asia Pacific Performing Arts Centres and a recipient of the Presidential Commendation at the 60th Republic of Korea Culture and Arts Awards.", "links": [{"title": "별빛이 내리는 계촌클래식축제 (한국경제)", "url": "https://www.hankyung.com/article/202606071280i"}] },
    "르네 노리스": { "kor": "스텐드 퍼포밍 아츠의 예술 및 교육 디렉터다. 텍사스 웨슬리안 대학교에서 연극과 영어를 전공하고 텍사스 우먼스 대학교 대학원 과정을 이수했다. 달라스와 포트워스 지역의 여러 학교 및 극단에서 연출과 교육 활동을 펼쳐왔다. 연극 연출과 안무, 교사 트레이닝 분야에서 풍부한 경력을 쌓았으며 다양한 무대에 배우로 출연하기도 했다.", "eng": "Artistic and Education Director at STAND Performing Arts. She holds a B.A. from Texas Wesleyan University and completed graduate studies at Texas Woman’s University. She has directed and taught at schools and theatres throughout the Dallas–Fort Worth area. With extensive experience in directing, choreography, and teacher training, she has also performed in various stage productions.", "links": [{"title": "STAND Performing Arts - Team", "url": "https://standperformingarts.org/team"}] },
    "오치 요이치": { "kor": "일반사단법인 봇짱극장의 대표이사다. 창립 20주년을 맞이한 일본 유일의 리저널 뮤지컬 극장을 운영하고 있으며, 세계 최초로 8K 원샷 무대영상을 제작한 프로듀서이기도 하다. 대만과 한국 배우가 참여하는 국제 뮤지컬을 전개하는 등 아시아 문화교류 사업을 적극적으로 추진하고 있다.", "eng": "Representative Director of Botchan Theatre. Managing Japan’s only regional musical theater company celebrating its 20th anniversary, he is also an 8K stage imaging producer who created the world’s first 8K one-shot stage presentation. He actively promotes Asian cultural exchange by developing international musicals featuring Taiwanese and Korean actors.", "links": [{"title": "Botchan Theater (Tourism Matsuyama)", "url": "https://en.matsuyama-sightseeing.com/spot/150-2/"}] },
    "권은정": { "kor": "글로벌문화교류위원회 위원장이다. 영국 에든버러 코리안시즌과 호주 애들레이드 코리안시즌의 예술감독으로 활약하고 있다. 서울아츠어워즈 심사위원장, 에이투비즈 대표이사 겸 예술감독, 런던특집행사추진단 단장, K-아트홀 극장장 등 다방면에서 문화 예술 교류를 이끌어왔다. 축제 에세이 '페스티벌 피플'을 집필했으며 2012년 문화체육관광부 장관 표창을 수상했다.", "eng": "Chair of the Global Cultural Exchange Committee. She serves as the Artistic Director for both the Edinburgh and Adelaide Korean Seasons. Her extensive leadership roles include Jury Chair for the Seoul Arts Awards, CEO and Artistic Director of AtoBiz, Director of the City of London Festival Organizing Committee, and CEO and Artistic Director of K-Art Hall. She is the author of the essay 'Festival People' and received a commendation from the Minister of Culture, Sports and Tourism in 2012.", "links": [] },
    "이종규": { "kor": "사단법인 한국뮤지컬협회 이사장이다. 현재 한국연극인복지재단 이사와 대한민국 뮤지컬페스티벌 프로듀서를 겸임하고 있다. 과거 인터파크씨어터 대표이사를 역임하며 블루스퀘어 등 주요 문화시설 총괄을 맡았고, 뉴컨텐츠컴퍼니 대표이사로서 뮤지컬 '벤허'와 '프랑켄슈타인'을 제작했다. 문화체육관광부를 비롯한 다수 지자체와 기관의 문화정책 자문위원으로도 활발히 활동 중이다.", "eng": "Chairman of the Korea Musical Theatre Association. He also serves as a board member of the Korea Theater Artists Welfare Foundation and the producer of the Korea Musical Festival. Previously, he was the CEO of Interpark Theater, managing major cultural venues like Blue Square, and produced hit musicals such as 'Ben-Hur' and 'Frankenstein' as the CEO of New Contents Company. He actively serves as a cultural policy advisor for the Ministry of Culture, Sports and Tourism and various local governments.", "links": [{"title": "\"넥스트 K-콘텐츠는 뮤지컬\" (뉴시스)", "url": "https://www.newsis.com/view/NISX20260402_0003575998"}] },
    "송승환": { "kor": "배우이자 공연 제작자로, PMC프러덕션 회장 겸 예술총감독을 맡고 있다. 1997년 초연한 넌버벌 퍼포먼스 '난타'를 세계 61개국 326개 도시에서 1,500만 명 이상이 관람한 대표적 한류 공연으로 키워냈으며, 2018 평창동계올림픽 개·폐회식 총감독을 맡았다.", "eng": "Song Seung-whan is an actor and producer, Chairman and Artistic Director of PMC Production. He created NANTA, seen by over 15 million people across 61 countries, and directed the ceremonies of the PyeongChang 2018 Winter Olympics.", "links": [{"title": "송승환 PMC프로덕션 회장 (서울경제)", "url": "https://www.sedaily.com/NewsView/1HLZQZZRP2"}] },
    "박창식": { "kor": "한국국제문화교류진흥원(KOFICE) 원장이며, 제19대 국회의원을 지냈다.", "eng": "President of KOFICE (Korea Foundation for International Cultural Exchange) and a former member of the 19th National Assembly.", "links": [] },
    "최원석": { "kor": "프로젝트 렌트 및 필라멘트앤코의 대표이자 공간기획자다. 현대카드와 LG전자를 거쳐 누적 250여 개의 팝업스토어를 기획·운영해 왔으며, 서울 뷰티트래블위크와 오늘전통축제 총감독을 역임했다. 저서로 오프라인 공간의 가치를 다룬 『결국, 오프라인』이 있다.", "eng": "CEO of Project Rent and Filament&co. With a background at Hyundai Card and LG Electronics, he has directed over 250 pop-up stores, defining offline spaces as a new form of media. He also served as the General Director for the Seoul Beauty Travel Week and the Today Traditional Festival, and authored the book After All, Offline.", "links": [] },
    "호리코시 마사카츠": { "kor": "일본 시부카와시 부시장이다. 군마현청 입청 후 기획부 종합정책실장, 생활아동부 차장, 총무부장 등을 역임하며 공공 행정 및 지역 정책 분야의 경력을 쌓았다. 군마현 국민건강보험단체연합회 상무이사를 거쳐 시부카와시 부시장으로 재임 중이다.", "eng": "Vice Mayor of Shibukawa City, Japan. After joining the Gunma Prefectural Government, he built an extensive career in public administration and local policy, serving as the Head of the Comprehensive Policy Office, Deputy Director of the Lifestyle and Children's Affairs Department, and Director General of the General Affairs Department. He also served as Managing Director of the Gunma Prefectural Federation of National Health Insurance Organizations.", "links": [] },
    "김대권": { "kor": "대구 수성구의 제 17, 18, 19대 수성구청장(지방고시 1회)이다. 공직 사회에서 쌓은 풍부한 행정 경험을 바탕으로, 현재 수성구를 교육·문화·예술 중심의 차별화된 글로벌 미래 도시로 이끌고 있다.", "eng": "The 17th, 18th, and 19th Mayor of Suseong-gu, Daegu, who passed the 1st Local Higher Civil Service Examination. Leveraging his extensive administrative experience in public service, he is currently leading Suseong-gu into a distinctive, global future city centered on education, culture, and the arts.", "links": [] },
    "서민교": { "kor": "대구대학교 경영학부 명예교수다. 대구대학교 경상대학 학장과 총장직무대행을 지냈으며, 한국국제경영학회, 한국국제경영관리학회, 한국산업경영학회, 한국인터넷전자상거래학회 회장을 역임하는 등 오랜 기간 국내 경영학계의 연구와 발전을 이끌어왔다.", "eng": "Professor Emeritus in the Department of Business Administration at Daegu University. He previously served as the Dean of the College of Business and Economics and Acting President of Daegu University. He has also led the academic community, serving as President of various institutions including the Korean Academy of International Business (KAIB) and the Korean Academy of International Business Management (KAIBM).", "links": [] },
    "리차드 페이": { "kor": "상하이 문화광장 총괄매니저다. 20년 이상의 경력을 지닌 중국 대표 뮤지컬 전문가이며, '오페라의 유령' 등 20여 편의 세계적 명작을 중국에 소개하고, 다수의 중국어 버전 뮤지컬을 제작했다. 상하이 국제 뮤지컬 페스티벌 기획과 창작 뮤지컬 육성 프로젝트를 이끌었으며, 2024년 쇼 라이프 뮤지컬 어워즈 사무총장으로 임명되었다.", "eng": "He is the General Manager of Shanghai Culture Square Theatre Management. With over 20 years of experience, he is a leading musical theatre expert in China. He has introduced over 20 world-famous musicals to China, including 'The Phantom of the Opera', and produced numerous Chinese-language version musicals. He has led the curation of the Shanghai International Musical Festival and the Original Musical Cultivation Project, and was appointed Secretary-General of the SHOW LIFE- Musical Awards in 2024.", "links": [] },
    "황길정": { "kor": "주식회사 소통파이브의 공동설립자이자 대표이사다. 한국대학창업협회 회장과 대경AX협회 의장을 맡고 있으며 , 네스트 CBDO, 한국비즈커넥트 COO 등을 역임했다. 행정안전부 국민정책디자인단 서비스디자이너, 서울시 120다산콜재단 운영자문위원으로도 활동 중이다. 현재 경북대학교 융합기술경영학과 석사과정에 재직하며 비즈니스 AX 및 DX 컨설팅 전문가로 활약하고 있다.", "eng": "Co-founder and CEO of Sotong Five. He serves as the Chairman of the Korea University Startup Association and the Chairman of the Daegyeong AX Association. He previously held executive roles including CBDO at Nest and COO at Korea Biz Connect. He also works as a service designer for the Ministry of the Interior and Safety’s National Policy Design Group and an advisory member for the Seoul 120 Dasan Call Foundation. Currently pursuing a master's degree in Convergence Technology Management at Kyungpook National University, he actively provides consulting on business AX and DX.", "links": [] },
    "정수현": { "kor": "주식회사 앤스페이스의 창업자이자 대표이사다. 공간공유 플랫폼 '스페이스클라우드' 사업과 서울사회주택리츠 1호 '앤스테이블' 주택 개발 및 운영을 총괄하고 있다. 무중력지대 대방동 센터장을 역임했으며 , 행정안전부 소통협력센터 자문위원 등으로 활동했다. 한동대학교를 졸업하고 고려대학교 정책대학원 석사과정에 재직 중이다.", "eng": "Founder and CEO of NSpace. She oversees the business operations of SpaceCloud, a space-sharing platform, and manages the development and operation of NStable, the No. 1 Seoul Social Housing REITS. She previously served as the director of the Youth Space 'Mu-jung-ryeok-ji-dae' in Daebang-dong and as an advisory member for the Ministry of the Interior and Safety's Communication and Cooperation Center. She graduated from Handong Global University and is currently pursuing a master's degree at Korea University's Graduate School of Policy.", "links": [] },
    "최경희": { "kor": "소풍커넥트 대표다. 스타트업 '튜터링'을 공동 창업해 공동 대표를 지냈으며, 마켓디자이너스 최고문화책임자(CCO)를 역임했다. 이후 투자사 소풍(Sopoong)의 파트너로서 IT 플랫폼, 서비스형 소프트웨어(SaaS), 대체육 등 기후변화 및 소셜벤처 분야의 투자와 액셀러레이팅을 총괄했다.", "eng": "CEO of Sopoong Connect. She previously co-founded and served as Co-CEO of Tutoring, and worked as Chief Culture Officer (CCO) at Marketdesigners. As a partner at Sopoong, she specialized in investing in and accelerating social ventures, focusing on IT platforms, SaaS, alternative meats, and climate change initiatives.", "links": [] }
  },
  "archive": [
    {
      "year": "2025", "edition": "6th", "poster": "",
      "kor": { "title": "Culture-based Co-operations, Enhancing the SDG's", "desc": "제6회 WCIF는 'Culture-based Co-operations, Enhancing the SDG's' 슬로건 아래, 한·일 수교 60주년을 기념한 문화·기술 협력과 글로벌녹색성장(Global Green Growth)을 두 축으로 진행되었습니다. 10월 29일(수) 웨스틴조선 서울 라일락홀에서, '한·일 문화기술 협력 - 문화산업 및 AI 서밋'(트랙1)과 GGGI 공동주최 '파리협정 10주년 문화의 밤'(트랙2)이 열렸습니다." },
      "eng": { "title": "Culture-based Co-operations, Enhancing the SDG's", "desc": "The 6th WCIF, held under the slogan 'Culture-based Co-operations, Enhancing the SDG's,' centered on two pillars: cultural and technological cooperation marking the 60th anniversary of Korea-Japan diplomatic relations, and Global Green Growth. Held at the Westin Josun Seoul on October 29, it featured the Korea-Japan Culture & Technology Summit (Track 1) and, co-hosted with GGGI, a Cultural Night marking the 10th anniversary of the Paris Agreement (Track 2)." },
      "speakers": { "kor": ["오부치 유코", "반기문", "주호영", "김상협", "이장우", "송승환", "김유원", "김용태", "이영복", "윤민호", "장사익", "KARD"], "eng": ["Obuchi Yuko", "Ban Ki-moon", "Joo Ho-young", "Kim Sang-hyup", "Lee Jang-woo", "Song Seung-whan", "Kim Yu-won", "Kim Yong-tae", "Lee Young-bok", "Yoon Min-ho", "Jang Sa-ik", "KARD"] },
      "videos": [],
      "photos": []
    },
    {
      "year": "2024", "edition": "5th", "poster": "",
      "kor": { "title": "문화와 기술의 융합으로 열어가는 미래교육", "desc": "제5회 WCIF는 AI시대 새로이 열리는 미래기회들과 교육의 미래를 조망함으로써 인재육성과 교육 방향에 관한 전략적 시사점을 도출했습니다. 문화, 콘텐츠, 과학, 기술 등 다양한 분야간 소통과 협력을 통해 WCIF의 비전인 '문화로 함께 하는 세상' Culture Universe를 이루어나가는 데 기여했습니다." },
      "eng": { "title": "Future Education through the Fusion of Culture and Technology", "desc": "The 5th WCIF examined the new opportunities of the AI era and the future of education, drawing strategic insights on talent development through dialogue across culture, content, science, and technology." },
      "speakers": { "kor": ["이수만", "이진형", "염재호", "강은희", "한경구", "백순근", "김용태", "전인건", "김대권"], "eng": ["Lee Soo-man", "Lee Jin-hyung", "Yeom Jae-ho", "Kang Eun-hee", "Han Kyung-koo", "Baek Soon-geun", "Kim Yong-tae", "Jun In-kun", "Kim Dae-kwon"] },
      "videos": [
        { "id": "nSorK15xZP0", "title": "Fusion of Culture and Technology for a New Educational Future" },
        { "id": "zXIoLf7lcMU", "title": "Our Educational Futures in the AI Age" },
        { "id": "iNes7x_vNO0", "title": "Local Education System for a New Educational Future" },
        { "id": "xy0Ga_dS0jY", "title": "Content Monetization for Producer-Type Creators" }
      ],
      "photos": []
    },
    {
      "year": "2023", "edition": "4th", "poster": "",
      "kor": { "title": "Creator Economy & Sustainability", "desc": "제4회 WCIF는 메타버스 세계 안에서의 창작자, 생산자, 소비자 등 새로운 혁신주체에 대해 논하고 미래 변화를 조망했습니다. 아세안 청년 크리에이터와 함께하는 창조경제 세션, 반기문 전 UN사무총장과 제인구달 박사가 참여한 Humanity and Sustainability 세션 등이 진행되었습니다." },
      "eng": { "title": "Creator Economy & Sustainability", "desc": "The 4th WCIF discussed the new innovators of the metaverse era and looked ahead to future change, featuring ASEAN young creators and a Humanity and Sustainability session with former UN Secretary-General Ban Ki-moon and Dr. Jane Goodall." },
      "speakers": { "kor": ["반기문", "제인구달", "이수만", "닉쿤", "최재천", "김해용", "앙겔라 타누수디조", "김용태"], "eng": ["Ban Ki-moon", "Jane Goodall", "Lee Soo-man", "Nichkhun", "Choi Jae-chun", "Kim Hae-yong", "Angela Tanoesoedibjo", "Kim Yong-tae"] },
      "videos": [
        { "id": "mbb-KWK3G50", "title": "Humanity and Sustainability" },
        { "id": "c02CjziUARs", "title": "Creative Economy with ASEAN Young People" },
        { "id": "FYD7UIhso9g", "title": "Creator IP Planning and Business Expansion Insights" }
      ],
      "photos": []
    },
    {
      "year": "2022", "edition": "3rd", "poster": "",
      "kor": { "title": "메타버스 시대: 음악과 엔터테인먼트 산업", "desc": "제3회 WCIF는 국내외 유명 프로듀서 및 기업인이 참여해 미래 문화산업의 흐름을 조망했습니다. 글로벌 협력, 메타버스와 엔터테인먼트 산업의 미래, AI와 NFT 기술의 활용을 주제로 The Sandbox 창업자 세바스찬 보르겟 등이 참여했습니다." },
      "eng": { "title": "The Metaverse Era: Music and Entertainment Industry", "desc": "The 3rd WCIF brought together renowned producers and entrepreneurs to survey the future of the cultural industry, covering global collaboration, the metaverse, and AI and NFT technologies, with speakers including The Sandbox founder Sebastien Borget." },
      "speakers": { "kor": ["이수만", "세바스찬 보르겟", "레밍턴 스콧", "차인혁", "헤이든 벨", "제스퍼 토르손", "이성수"], "eng": ["Lee Soo-man", "Sebastien Borget", "Remington Scott", "Cha In-hyuk", "Hayden Bell", "Jesper Thorsson", "Lee Sung-su"] },
      "videos": [
        { "id": "xXl3M75rY5c", "title": "[라이브중계] 2022 제3회 세계문화산업포럼" },
        { "id": "af177kgL65U", "title": "[Live Streaming] 2022 3rd WCIF" }
      ],
      "photos": []
    },
    {
      "year": "2021", "edition": "2nd", "poster": "",
      "kor": { "title": "문화와 기술의 융합", "desc": "제2회 WCIF는 세계 음악 및 엔터테인먼트 산업의 미래 변화를 조망하고 콘텐츠 창작자, 생산자, 유통자들 간 협력관계를 증진했습니다. 포스트 코로나 시대 산업의 변화, 4차 산업혁명 기술과 문화콘텐츠의 결합이 만들어내는 새로운 비즈니스 기회 등을 다루었습니다." },
      "eng": { "title": "Fusion of Culture and Technology", "desc": "The 2nd WCIF surveyed the future of the global music and entertainment industry, addressing post-pandemic industry change and new business opportunities from the fusion of 4th industrial revolution technology and cultural content." },
      "speakers": { "kor": ["이수만", "마크 버넷", "테디 지", "후위", "김상엽", "아키모토 야스시", "aespa"], "eng": ["Lee Soo-man", "Mark Burnett", "Teddy Zee", "Hu Yu", "Kim Sang-yeop", "Yasushi Akimoto", "aespa"] },
      "videos": [
        { "id": "5IdBrpOdWxI", "title": "[메인세미나] 2021 세계문화산업포럼 (한국어)" },
        { "id": "FVd5F_pNmhI", "title": "[Main Seminar] 2021 WCIF (English)" },
        { "id": "mDSLtgdlb84", "title": "[티저] 문화와 기술의 융합" }
      ],
      "photos": []
    },
    {
      "year": "2020", "edition": "1st", "poster": "",
      "kor": { "title": "K-pop and Culture Universe", "desc": "제1회 WCIF는 세계 유명 프로듀서와 CEO들을 초청해 콘텐츠 제작자, 생산자, 유통자들 간 협력관계를 증진했습니다. BTS와 SuperM 등 빌보드 1위의 세계적 아이돌 그룹을 배출한 K-pop의 성공을 계기로 아시아와 서구를 잇는 가교의 역할을 시작했습니다." },
      "eng": { "title": "K-pop and Culture Universe", "desc": "The 1st WCIF invited world-renowned producers and CEOs to build cooperation among content creators, producers, and distributors, beginning its role as a bridge between Asia and the West on the momentum of K-pop's global success." },
      "speakers": { "kor": ["이수만", "스티브 바넷", "쿠로이와 카츠미", "롭 라이트", "백현", "보아"], "eng": ["Lee Soo-man", "Steve Barnett", "Katsumi Kuroiwa", "Rob Light", "Baekhyun", "BoA"] },
      "videos": [
        { "id": "0hMIGD7EmjM", "title": "[메인세미나] 2020 세계문화산업포럼 (한국어)" },
        { "id": "WUSthuKPwlw", "title": "[Main Seminar] 2020 WCIF (English)" },
        { "id": "nSLmnniU97g", "title": "[홍보영상] 2020 제1회 WCIF" }
      ],
      "photos": []
    }
  ],
  "news": {
    "notice": [
      { "date": "2026.04.28", "url": "https://wcif.world/media/notice/43", "kor": "「2026 WCIF」 위탁 운영 선정을 위한 적격자심의위원회(평가위원 후보자) 공개모집 공고", "eng": "2026 WCIF: Open Call for Evaluation Committee Candidates for Operating Agency Selection" },
      { "date": "2026.04.28", "url": "https://wcif.world/media/notice/41", "kor": "2026 WCIF 행사 운영 용역 입찰공고", "eng": "2026 WCIF Event Operation Service Tender Notice" },
      { "date": "2023.06.21", "url": "https://wcif.world/media/notice/33", "kor": "[2023WCIF] 발표자료_한국과학기술단체총연합회", "eng": "[2023 WCIF] Presentation: KOFST" },
      { "date": "2023.06.21", "url": "https://wcif.world/media/notice/32", "kor": "[2023WCIF] 발표자료_Cayman IP_Andrea Williams", "eng": "[2023 WCIF] Presentation: Cayman IP, Andrea Williams" },
      { "date": "2023.06.21", "url": "https://wcif.world/media/notice/30", "kor": "[2023WCIF] 발표자료_갤러리스탠 바이 아트컨시어지뉴욕", "eng": "[2023 WCIF] Presentation: Gallery STAN" },
      { "date": "2023.06.21", "url": "https://wcif.world/media/notice/29", "kor": "[2023WCIF] 발표자료_기술보증기금(KIBO)", "eng": "[2023 WCIF] Presentation: KIBO" },
      { "date": "2023.06.21", "url": "https://wcif.world/media/notice/28", "kor": "[2023WCIF] 발표자료_더에스엠씨그룹", "eng": "[2023 WCIF] Presentation: The SMC Group" },
      { "date": "2023.06.21", "url": "https://wcif.world/media/notice/27", "kor": "[2023WCIF] 발표자료_한국국제문화교류진흥원(KOFICE)", "eng": "[2023 WCIF] Presentation: KOFICE" },
      { "date": "2023.06.21", "url": "https://wcif.world/media/notice/25", "kor": "[2023WCIF] 발표자료_한아세안센터(AKC)", "eng": "[2023 WCIF] Presentation: ASEAN-Korea Centre" },
      { "date": "2023.05.09", "url": "https://wcif.world/media/notice/22", "kor": "「2023 WCIF」 위탁 운영 선정을 위한 적격자심의위원회 공개모집 공고", "eng": "2023 WCIF: Open Call for Evaluation Committee Candidates" }
    ],
    "press": [
      { "date": "2026.07.03", "url": "https://www.imaeil.com/page/view/2026070301522518657", "kor": "[매일신문] 수변 공연부터 AI 무대기술까지 K뮤지컬 미래 모색…대구서 열린 세계문화산업포럼", "eng": "[Maeil Shinmun] From waterside performances to AI stage tech: exploring the future of K-musicals at WCIF in Daegu" },
      { "date": "2026.07.02", "url": "https://www.idaegu.com/news/articleView.html?idxno=664063", "kor": "[대구일보] 대구 수성구 ‘제7회 세계문화산업포럼(WCIF)’ 개최", "eng": "[Daegu Ilbo] Daegu Suseong-gu opens the 7th World Culture Industry Forum (WCIF)" },
      { "date": "2026.06.30", "url": "https://www.news1.kr/life-culture/general-cultural/6212516", "kor": "[뉴스1] 세계문화산업포럼 7월 개막…도시 디자인부터 한일 협력까지", "eng": "[News1] World Culture Industry Forum opens in July: from urban design to Korea-Japan cooperation" },
      { "date": "2026.06.25", "url": "https://www.edaily.co.kr/News/Read?mediaCodeNo=257&newsId=06251686645485000", "kor": "[이데일리] 수성구, 내달 2~3일 세계문화산업포럼 개최…문화로 도시 미래 논한다", "eng": "[Edaily] Suseong-gu to host the World Culture Industry Forum on Jul 2-3, discussing the city's future through culture" },
      { "date": "2026.06.24", "url": "https://www.kyongbuk.co.kr/news/articleView.html?idxno=4076479", "kor": "[경북일보] 세계문화산업포럼 7월 대구 수성서 재개…글로벌 문화협력 허브 도약", "eng": "[Kyongbuk Ilbo] World Culture Industry Forum resumes in Daegu Suseong in July, leaping toward a global cultural-cooperation hub" },
      { "date": "2026.06.24", "url": "https://www.imaeil.com/page/view/2026062416044597681", "kor": "[매일신문] 수성구, 제7회 세계문화산업포럼 개최…문화도시 글로벌 협력 강화", "eng": "[Maeil Shinmun] Suseong-gu holds the 7th World Culture Industry Forum, strengthening the culture city's global cooperation" },
      { "date": "2026.06.17", "url": "https://www.idaegu.com/news/articleView.html?idxno=663676", "kor": "[대구일보] ‘혈세 낭비’ 논란 딛고…대구 수성구 ‘세계문화산업포럼’(WCIF) 실속 채워 돌아온다", "eng": "[Daegu Ilbo] Overcoming the 'tax waste' controversy, Daegu Suseong-gu's WCIF returns with substance" },
      { "date": "2024.07.11", "url": "https://www.lawissue.co.kr/view.php?ud=202407111941551441204ead0791_12", "kor": "[로이슈] 더에스엠씨그룹, 제5회 WCIF 참여 外", "eng": "[Lawissue] The SMC Group Participates in the 5th WCIF" },
      { "date": "2024.07.10", "url": "https://www.yeongnam.com/web/view.php?key=20240704010000704", "kor": "[영남일보] \"AI는 감성과 이성 결합한 명확한 가치관으로 발전해야\"", "eng": "[Yeongnam Ilbo] \"AI Must Develop with Clear Values Combining Emotion and Reason\"" },
      { "date": "2024.07.07", "url": "http://www.ksmnews.co.kr/news/view.php?idx=490694", "kor": "[경상매일신문] WCIF 폐막…AI 시대 교육의 미래 조망", "eng": "[Kyongsang Maeil] WCIF Closes with a Look at the Future of Education in the AI Era" },
      { "date": "2024.07.04", "url": "https://www.newsis.com/view/NISX20240704_0002799108", "kor": "[뉴시스] '미래와 교육' 2024 제5회 세계문화산업포럼 폐막", "eng": "[Newsis] 'Future and Education': The 5th WCIF Closes" },
      { "date": "2024.07.04", "url": "https://www.yeongnam.com/web/view.php?key=20240704010000685", "kor": "[영남일보] 이수만 \"한국은 프로듀서의 나라 되어야\"", "eng": "[Yeongnam Ilbo] Lee Soo-man: \"Korea Must Become a Nation of Producers\"" },
      { "date": "2024.07.04", "url": "https://www.yeongnam.com/web/view.php?key=20240704010000625", "kor": "[영남일보] \"더에스엠씨그룹의 미래는 뉴 엔터테인먼트의 고민\"", "eng": "[Yeongnam Ilbo] \"The SMC Group's Future Lies in New Entertainment\"" },
      { "date": "2024.07.03", "url": "https://www.kyongbuk.co.kr/news/articleView.html?idxno=4013236", "kor": "[경북일보] AI와 문화의 시대 우리의 미래…세계문화산업포럼 대구서 개막", "eng": "[Kyongbuk Ilbo] WCIF Opens in Daegu: Our Future in the Age of AI and Culture" },
      { "date": "2024.07.03", "url": "https://www.yeongnam.com/web/view.php?key=20240703010000519", "kor": "[영남일보] AI 시대, 대구의 교육 혁신", "eng": "[Yeongnam Ilbo] Daegu's Education Innovation in the AI Era" },
      { "date": "2024.07.03", "url": "https://www.yeongnam.com/web/view.php?key=20240703010000557", "kor": "[영남일보] 김대권 수성구청장 \"AI시대 맞춤형 교육정책 논의하자\"", "eng": "[Yeongnam Ilbo] Suseong Mayor Kim Dae-kwon Calls for Tailored Education Policy in the AI Era" },
      { "date": "2024.07.02", "url": "https://www.yeongnam.com/web/view.php?key=20240701010000029", "kor": "[영남일보] AI 시대 문화·기술 융합으로 인한 교육의 미래 조망…제5회 세계문화산업포럼(WCIF)", "eng": "[Yeongnam Ilbo] The 5th WCIF: The Future of Education through the Fusion of Culture and Technology" }
    ]
  }
};
